spring:
  application:
    name: se24-demo
  autoconfigure:
    exclude: # prevent issues with Spring searching for database while we have not discussed Docker in the lectures yet
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #datasource:
  #  driver-class-name: org.postgresql.Driver
  #flyway:
  #  enabled: true
  #  locations: classpath:db/migration
  #  validate-on-migrate: true

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
